# HCF Config
motd-text: '&l&cSmooth &9HCF'

# Faction config
faction.max-members: 6
faction.regen-cooldown: 900
faction.home-cooldown: 15
faction.stuck-cooldown: 40
faction.claim-price-per-block: 100
faction.strike-webhook: ''